### ISSUE TITLE
scapri created a mess in the repo - please fix it

### ISSUE THREAD

**Issue by scapri** [ambientsensors/class-repo#13]
Look at all of the horrid PRs that you messed up - please fix

**Comment by scapri** [comment]
Fixed 10 branches, 2 left - not going to fix because it would break too much.

**Comment by ehlangework** [comment]
Must have been ciaodog's last commit. No biscuits today :|

**Comment by scapri** [comment]
No biscuits for @ciaodog?  Then no doughnuts for you!!! :-P
